language: python

cache: pip

matrix:
  include:
  - python: "2.7"
    env: HADOOP_MAJOR_VERSION=2
  - python: "2.7"
    env: HADOOP_MAJOR_VERSION=3
  - python: "3.6"
    env: HADOOP_MAJOR_VERSION=3
  - python: "3.7"
    env: HADOOP_MAJOR_VERSION=3
    dist: xenial

sudo: required

services: docker

before_install: pip install flake8

# skip installation, requirements are handled in the Docker image
install: true

before_script:
  - flake8 -v .
  - DEBUG=true ./.travis/check_script_template -v

script:
 - docker build --build-arg HADOOP_MAJOR_VERSION=${HADOOP_MAJOR_VERSION} -t crs4/pydoop .
 - docker run --rm --name pydoop -d crs4/pydoop
 - "docker exec pydoop bash -c 'while : ; do jps | grep DataNode && break; done'"
 - DEBUG=true ./.travis/run_checks
 - docker stop pydoop
 # Needs to run only once. For balance, add this to the fastest job
 - if ([ "${TRAVIS_PYTHON_VERSION}" = "2.7" ] && [ "${HADOOP_MAJOR_VERSION}" = "2" ]); then docker build -t crs4/pydoop-docs -f Dockerfile.docs .; fi

deploy:
  provider: script
  script: .travis/deploy
  on:
    python: "3.6"
    condition: $HADOOP_MAJOR_VERSION = 3
    repo: crs4/pydoop
    tags: true
