language: python

cache: pip

matrix:
  include:
  - python: "2.7"
    env: HADOOP_VERSION=3.2.0
  - python: "3.6"
    env: HADOOP_VERSION=2.9.2
  - python: "3.6"
    env: HADOOP_VERSION=3.2.0
  - python: "3.6"
    env: HADOOP_VERSION=3.2.0 LOCAL_FS=true
  - python: "3.7"
    env: HADOOP_VERSION=3.2.0
    dist: xenial

sudo: required

services: docker

before_install: pip install flake8

# skip installation, requirements are handled in the Docker image
install: true

before_script:
  - flake8 -v .
  - python .travis/check_script_template.py -v
  - docker build -t crs4/pydoop-docs -f Dockerfile.docs .

script:
 - ./.travis/start_container
 - ./.travis/run_checks
 - docker stop pydoop

before_deploy:
  - pip install setuptools twine wheel

deploy:
  provider: script
  script: .travis/deploy
  on:
    python: "3.6"
    condition: $HADOOP_VERSION = 3.2.0
    repo: crs4/pydoop
    tags: true
